name: Daily Backup

on:
  workflow_dispatch:       # This lets you run manually from GitHub UI
  schedule:
    - cron: '0 0 * * *'   # Runs daily at midnight UTC
  push:
    branches:
      - main

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create zip file
        run: zip -r backup.zip .

      - name: Send backup email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_APP_PASSWORD }}
          to: ${{ secrets.EMAIL_RECEIVER }}
          subject: Daily Backup - ${{ github.repository }}
          body: "Backup of repository attached."
          attachments: backup.zip
          secure: true
