name: Auto Backup to GitHub

on:
  push:
    branches:
      - main

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Commit backup
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.name "Auto Backup Bot"
        git config --global user.email "autobackup@example.com"
        git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/LegacyArtCollective/legacyartcollective.github.io.git
        git add .
        git commit -m "Auto backup commit by GitHub Actions" || echo "No changes to commit"
        git push origin main




