name: Daily Backup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create timestamp variable
        id: vars
        run: echo "BACKUP_NAME=backup-$(date +'%Y-%m-%d_%H-%M-%S').zip" >> $GITHUB_ENV

      - name: Create zip file with timestamp
        run: zip -r ${{ env.BACKUP_NAME }} .

      - name: Send backup email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: EastMeridianCollections@gmail.com
          password: ${{ secrets.EMAIL_APP_PASSWORD }}
          from: EastMeridianCollections@gmail.com
          to: EastMeridianCollections@gmail.com
          subject: Daily Backup - LegacyArtCollective/legacyartcollective.github.io
          body: "Backup of repository attached."
          attachments: ${{ env.BACKUP_NAME }}
          secure: true
