name: Google Drive Auto Backup

on:
  workflow_dispatch:       # manual trigger
  schedule:
    - cron: '0 2 * * *'    # daily at 2:00 AM UTC

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install rclone
      run: |
        curl https://rclone.org/install.sh | sudo bash

    - name: Setup rclone config
      run: |
        mkdir -p ~/.config/rclone
        echo "${{ secrets.GDRIVE_CREDENTIALS }}" > ~/.config/rclone/rclone.conf

    - name: Create timestamped backup zip
      run: |
        TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
        zip -r backup-$TIMESTAMP.zip .

    - name: Upload backup to Google Drive
      run: |
        TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
        rclone copy backup-$TIMESTAMP.zip gdrive:"${{ secrets.GDRIVE_FOLDER_ID }}" --progress

    - name: Send backup notification email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_APP_PASSWORD }}
        to: ${{ secrets.EMAIL_RECEIVER }}
        from: ${{ secrets.EMAIL_USERNAME }}
        subject: "Google Drive Backup Complete - ${{ github.repository }}"
        body: "Backup uploaded to Google Drive successfully."
